apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
   user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;


        server {
            listen 80;

            location / {
                proxy_pass         http://tomcat-one:8080/;
                proxy_redirect     off;
            }
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: nginx
    image: "avinashsi/nginx:1.14.0-1_R2"
    imagePullPolicy: IfNotPresent 
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: nginx-conf
---
kind: Service
apiVersion: v1
metadata:
  name: frontend 
spec:
  type: NodePort    
  ports:
  - port: 80
    nodePort: 32080 
  selector:
    app: frontend
